# Generated by Django 4.2.2 on 2024-04-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
    ]
